### ISSUE TITLE
Connecting srsRAN gNB to OSC RIC

### ISSUE THREAD

**Issue by aliasadi2001** [wineslab/xDevSM#1]
Hello everyone,

I have installed the RIC and PM xApp along with their corresponding pods, as shown in the image below:

![Screenshot from 2024-10-10 15-03-58](https://github.com/user-attachments/assets/5705ff9f-28b6-4a0e-86c1-201ba3ade6be)

I am trying to connect a gNB (srsRAN gNB), but I encountered the following error:

![Screenshot from 2024-10-10 15-08-07](https://github.com/user-attachments/assets/0ac33d02-5a77-4f4c-ad03-005988fcc89c)

The IP addresses 10.244.0.13 and 10.244.0.12 correspond to the E2Term and E2Mgr, respectively.

Do we need to set the bind_address in the E2 section? If so, what IP should we use, and how can I find it?

It's also worth noting that the Open5GS core connects successfully, but it disconnects due to the E2 connection refusal, as indicated in the following image:

![Screenshot from 2024-10-10 15-11-46](https://github.com/user-attachments/assets/784486c4-f861-41fd-8ae5-cb857da5bd65)

Thank you for your help! I would greatly appreciate any assistance.

**Comment by aferaudo** [comment]
Thanks for this question - this repo and related issues should be focused on xDevSm and issues with using the xApp framework.
For your query, I suggest trying the following: use the `--bind_addr="<ip_address_local_interface>"` option, where `<ip_address_local_interface>` should be replaced with the IP address of the local interface of the gNB connected to the Near-RT RIC. For more details, please refer to the [official guide](https://docs.srsran.com/projects/project/en/latest/tutorials/source/near-rt-ric/source/index.html#id7) .

**Comment by aliasadi2001** [comment]
Hi @aferaudo 
Thank you for your response 
Best regards

**Comment by hududed** [comment]
@aliasadi2001 did you find a solution to this?
